[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
test_framework = unity
test_build_src = false
lib_deps =
    adafruit/Adafruit Fingerprint Sensor Library
    pololu/VL53L0X
    h2zero/NimBLE-Arduino
    throwtheswitch/Unity@^2.6.1
